services:
  docs:
    image: rule_engine_api_local_docs
    container_name: rule_engine_api_local_docs
    build:
      context: .
      dockerfile: ./compose/local/docs/Dockerfile
    env_file:
      - ./.envs/.local/.django
    volumes:
      - ./docs:/docs:z
      - ./config:/app/config:z
      - ./rule_engine_api:/app/rule_engine_api:z
    ports:
      - '9000:9000'
    command: /start-docs
