# Generated by Django 5.1.11 on 2025-07-03 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_role',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('CLIENT', 'Client')], default='CLIENT', max_length=10),
        ),
    ]
